### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by edvwib** [edvwib/Webshop#1]
Your final assignment for this course will be to create a webshop. Your grade will be dependent on this assignment only. You are free to use whatever you want for the frontend, it does not have to be done in MVC. As long as you build your backend in C#, you can run it as an API.

----------
**Minimum requirements:**

- [x] Backend needs to be built in C#
- [x] List products
- [x] Cart
- [x] Checkout
- [x] Information about the items
- [x] Fields for customer information
- [x] Git (And not everything in one commit please!)
- [x] At least one unit test
- [x] Tested by at least one of your class mates.
- [x] And all of this needs to be saved into a DB. 

*You do not need to create a nice design. CSS/HTML is not what this course is about. But the site still needs to be usable.*

----------
**Extras:**

- [ ] Admin tools for adding and editing products

- [ ] Admin tools for handling a order

- [ ] Secure your admin tools with auth

- [x] Product page

- [ ] Register as customer

***Deadline: 19th of April. On this date you will have to present your work to me and the class!***
